id: PED1012D4
initial_creation_type: input
source_metadata:
  Title: Śrīsahajasiddhi
  Editor: Malati J. Shendge
  Publisher: Indo-Iranian Journal
  Place of Publication: Tokyo
  Year: '1967'
  Śrīsahajasiddhi:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:11:07.938785'
last_modified_at: '2022-03-08T17:11:07.938793'
